name: Build
on:
  push:
    branches:
      - master
      - release/*
    paths:
      - '**.js'
jobs:
  build:
    name: my job Den
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [macos-latest]
        node: [10, 12]
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node }}
      - run: npm ci 
      - run: npm run build --if-present 